apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: cross-encoder-mlflow
  namespace: seldon
spec:
  name: cross-encoder-mlflow
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: MLSERVER_MODELS_DIR
            value: /mnt/models
          name: cross-encoder-mlflow
    graph:
      children: []
      envSecretRefName: seldon-rclone-secret
      implementation: CUSTOM_IMPLEMENTATION
      modelUri: s3://mlflow/0/d3ac0e6fa8824a2980b8041c05612b66/artifacts/cross_encoder_pyfunc
      name: cross-encoder-mlflow
    name: cross-encoder-mlflow
  protocol: v2
